### ISSUE TITLE
stateiconinfo error

### ISSUE THREAD

**Issue by AtomixRO** [ROClientSide/Translation#18]
Hello,
I've just pulled today's git and i've got the following error on stateiconinfo:
[string "buf"]:5018 table index is nill.

I've used GRF editor to update my grf and i'm also using 2013-08-07 client

**Comment by dastgir** [comment]
@AtomixRO 
I will look into it, and will push a fix(if found any error)

**Comment by dastgir** [comment]
@AtomixRO 
There's no such error for me from stateiconinfo,
Please post a screenshot(and if possible stateiconinfo and recheck if its updated)

**Comment by AtomixRO** [comment]
![state](https://cloud.githubusercontent.com/assets/214579/5739269/eec39f16-9bf7-11e4-9e76-9bb643486071.jpg)

And it's the latest file from git but here what i have in my file:
http://pastebin.com/VYVfXqZe

**Comment by dastgir** [comment]
Be sure you have latest efstids.lub
(Also, the line 5018 should not give error, since its just a bracket, maybe your GRF is reading some other StateIconInfo)??

**Comment by AtomixRO** [comment]
That was it. Thank you.
