### ISSUE TITLE
Big inventory windows

### ISSUE THREAD

**Issue by AtomixRO** [ROClientSide/Translation#19]
Hey it's me again.
I was wondering what's the file name to fix the big inventory windows:
![inv](https://cloud.githubusercontent.com/assets/214579/5744172/8bd8c5da-9c1e-11e4-92a4-e0dd8c4312e5.jpg)
Thanks

**Comment by zackdreaver** [comment]
msgstringtable.txt

**Comment by zackdreaver** [comment]
um, btw,
its better to report/ask in forum instead of issue section

**Comment by AtomixRO** [comment]
Yeah sorry about that. The thing is that i don't know "your" forum. I appeared to be lucky to find this repo months ago from a random post on rAthena.

**Comment by dastgir** [comment]
We don't have any forum, we have a dedicated topic on hercules forum, and that's the only one we use(any this github issues)
@zackdreaver 
Using of github issues for this kind of problem is fine, since we can respond faster here.

@AtomixRO 
there's several MsgStringtable.txt on data/MsgString/ folder, replace one of them(the date nearest to the client date you chosen) with the original msgstringtable.txt

**Comment by AtomixRO** [comment]
Sorry about the late reply, thanks for the info but i still couldn't find your dedicated topic onhercules forum. Could you please give me a direct link ?

I've got a new issue with Gunslinger "Flip the Coin skillid 501". It's the wrong icon being used ingame and get the follow error all the time:
![coin fling error](https://cloud.githubusercontent.com/assets/214579/6131481/972e90ca-b14c-11e4-922d-33cec5f0171c.jpg)

Last time i've updated my descriptions was on the 01/23. Could you light me up on where I could fix the icon issue please ?

**Comment by dastgir** [comment]
@AtomixRO, I will check into issue, most probably, you need to update your kRO , or maybe we miss that icon in our repo..

**Comment by AtomixRO** [comment]
My kRO is up to date and there isn't any coin fling.bmp in any grf. I didn't have this problem 2 months ago so I assume something has been updated in skills descriptions file or I don't know which one has changed the skill icon. I've tried to add a custom the right image from rms with coin fling.bmp but no luck on solving the issue.

**Comment by zackdreaver** [comment]
@dastgir 
why don't we update README.md so it has link to our forum
many *athena user use this project without knowing where is our forum.

**Comment by dastgir** [comment]
@zackdreaver 
Commited with link to forum.

**Comment by zackdreaver** [comment]
coin fling bmp problem was fixed a few weeks ago.
i think its ok close this
