### ISSUE TITLE
viewID converter on SeperateItemInfo

### ISSUE THREAD

**Issue by zackdreaver** [ROClientSide/Translation#20]
Hi,
is it possible to make SeperateItemInfo convet into item_db.txt that contain viewID
something like this inside item_db.txt :
9999,,,,,,,,,,,,,,,,,,777,{},{},{}
9999 is item id
777 is viewID

thank you

**Comment by dastgir** [comment]
Possible...., however I would add it for .conf, and use my other tool for converting it to .txt

**Comment by zackdreaver** [comment]
wo hoo that's cool
yeah for .conf is good too.
thank you.

**Comment by zackdreaver** [comment]
Any news?

**Comment by dastgir** [comment]
What happens if item in item_db is not found but found in iteminfo? Just error??

**Comment by zackdreaver** [comment]
its only seeking the view id of the item inside item_db, no errors will showed if there no items

i want to use it with this
https://rathena.org/board/files/file/2448-itemconverter/
