### ISSUE TITLE
prontera error

### ISSUE THREAD

**Issue by ernestfegarido** [ROClientSide/Translation#22]
good day sir! can you fix the prontera map because whenever i go to prontera the client crashes. thank you in advance sir! :)

**Comment by dastgir** [comment]
@zackdreaver, should we upload prontera file to repo(I think bad idea, since it would make repo more bigger)

@topicstarter, it is because, prontera has been updated in kRO, with new models and new effects, which requires new client(2015-02-26+)

**Comment by ernestfegarido** [comment]
so sir @dastgir what is the best way to get rid of it? :) thank you sir :)

**Comment by zackdreaver** [comment]
@dastgir
We should not, because we focus on translating right?
@ernestfegarido
There is old prontera map uploaded in herc
http://hercules.ws/board/files/file/182-old-prontera/

**Comment by ernestfegarido** [comment]
@zackdreaver so if i use that old prontera files my client will not crash anymore? :)

**Comment by zackdreaver** [comment]
yes

**Comment by ernestfegarido** [comment]
@zackdreaver thank you sir! ill try it now :)

**Comment by rexyflexx** [comment]
@zackdreaver  thank you for that sir, at least now i can go to prontera and inside the castle as well, but still i can't go inside the church/sanctuary or any other buildings in prontera, still crashes :( any other solution? TIA
