### ISSUE TITLE
missing win_bank.bmp translation 

### ISSUE THREAD

**Issue by reigneil** [ROClientSide/Translation#24]
is there any translation of this?
off topic: may i ask also where are all those items from different country?

**Comment by zackdreaver** [comment]
@reigneil what items?

**Comment by reigneil** [comment]
what i mean is the sprites and textures from pRO,jRO etc. where are they now? btw thanks for quick fix... i am a huge fan of this project. :+1:

**Comment by zackdreaver** [comment]
i delete it,
it has nothing to do with translation.
You need to search it by yourself.

**Comment by reigneil** [comment]
would you mind if i ask where can i download it? i mean the last time that is still there... i feel bad that i didn't back it up.

**Comment by zackdreaver** [comment]
b5d817a3cdce0c277fb386f4138535323e386c5a
pull with this

**Comment by reigneil** [comment]
i never knew that it can be pulled again... a big thanks to you. :+1:
