### ISSUE TITLE
missing skill effects issue

### ISSUE THREAD

**Issue by reigneil** [ROClientSide/Translation#28]
our SkillEffectInfoList.lub is not updated to support Rebellion. btw may i ask why do we need to keep this and all _f.lub when they are already been translated by default in kRO files?

**Comment by zackdreaver** [comment]
its function files to prevent error caused by user who have non KRO/not updated client.

**Comment by dastgir** [comment]
Don't we already have updated lua? For _f and skilleffectinfolist?

**Comment by zackdreaver** [comment]
he mean the "SkillEffectInfoList.lub" files
i will update it after made some test
