### ISSUE TITLE
File cannot be read

### ISSUE THREAD

**Issue by Streusel** [ROClientSide/Translation#31]
The files inside: https://github.com/ROClientSide/Translation/tree/master/Pre-Renewal/data cannot be read by the client because they're saved in unicode.

**Comment by dastgir** [comment]
o_O My Git Client saves them as ANSI upon cloning.

**Comment by Streusel** [comment]
I downloaded it as a zip and it was unicode >-<

**Comment by zackdreaver** [comment]
dont download as zip...
use git

**Comment by dastgir** [comment]
Download should be from git, if it still persist, reopen the issue
