### ISSUE TITLE
Line mismatch (?) in msgstringtable.txt

### ISSUE THREAD

**Issue by eleriaqueen** [ROClientSide/Translation#32]
I downloaded client-side translation through GIT Website and set up my client for a personal test server, client used is 2013-08-07 but it doesn't matter. (in the zip file there is a version reference code c5e7cdc105eced92d9cd7258844de3e1db7bd1ee).
Anyway...

I think the following lines were inverted :

Complete#
During %d minutes your Exp will increase by %d%%.#

See screenie :
![screenrathena000](https://cloud.githubusercontent.com/assets/4411178/7920466/7b4bf53c-089f-11e5-8499-8d3409c20a91.jpg)

**Comment by zackdreaver** [comment]
There are different msgstringtable for each client
https://github.com/ROClientSide/Translation/tree/master/data/MsgString
btw,
there are no msgstringtable changed in c5e7cdc105eced92d9cd7258844de3e1db7bd1ee

**Comment by eleriaqueen** [comment]
Ohhh riiiight, sorry, I didn't know... I feel stupid now.
