### ISSUE TITLE
msgstringtable#L1629

### ISSUE THREAD

**Issue by cydh** [ROClientSide/Translation#33]
Somehow, I think the line that tells 'someone' won 'something' from 'box' has wrong translation (https://github.com/ROClientSide/Translation/blob/master/data/msgstringtable.txt#L1629)
> [%s] has won [%s] from '%s'.#

Yes, if according to iRO's msgstringtable.txt, the order was right and also if you put the msg

You'll notice it if u got item from box, it will result (just try it, by using Herc especially, since they implement the client message already)
> [Player Name] has won [BoxName] from 'ItemName'

But, if you see the kRO msgstringtable.txt RAW (https://github.com/ROClientSide/Translation/blob/master/Dev/KRO_RAW/data/msgstringtable.txt#L1629)
> [%s]님이 [%s](으)로부터 '%s' 를 획득 했습니다.#

if from Google translation, it'll be 'someone' has won 'something' from 'box', but if you want to translate the clauses separately, it becomes like 
> [%s]님이  --> [% s] for:
> [%s](으)로부터   --> [% s] (coming) from
> '%s' 를 획득 했습니다. --> It has won the '% s'.

Somehow it means
> 'someone' from 'box' has won 'something'.

Also, my Aegis client has the entry as
> Citizens of Midgard, Lady Luck shines upon [%s] !! [%s] has awarded the player with '%s' !!

**Comment by zackdreaver** [comment]
Yeah i found many transaltion from IRO is kinda "stupid"

that string you got was came from euRO and pRO
Should we use that @dastgir ?

**Comment by dastgir** [comment]
We should be focused on translation, we can't have translation either from euRO/pRO.
So we should either translate kRO or use iRO, but in this case, both almost means same.

User should customize it if they wish to.
Since there's many other strings too which have different granmer

**Comment by dastgir** [comment]
@zackdreaver , you may comment over here, for the final decision

**Comment by zackdreaver** [comment]
Fixed
https://github.com/ROClientSide/Translation/commit/713c23a148d2f8532acc82514210136b3fe7ce70
