### ISSUE TITLE
msgstringtable.txt

### ISSUE THREAD

**Issue by kyeme** [ROClientSide/Translation#37]
Hello,
When casting Asperio with no holy water i got this:
Unable to use the skill to exceed the number of Ancilla.#

When No Spirit Sphere i got this:
Requires %d mind bullets#

Im using 2013-12-23

**Comment by zackdreaver** [comment]
Mind elaborate how to produce Requires %d mind bullets# ?

**Comment by kyeme** [comment]
When using Body Relocation w/ no Dangerous Collect Soul you will get this msg.

**Comment by zackdreaver** [comment]
seems normal as i tested it
Requires 1 mind bullets
and that's how its work in official

**Comment by kyeme** [comment]
Is not "Need %d of Spirit Sphere" ?

**Comment by zackdreaver** [comment]
haven't made another test
but as i remember, it's used on gunslinger skill too
that's why it used mind bullet instead spirit sphere...

**Comment by dastgir** [comment]
3a06272be9fdcb4f5e78f741c395cc7c1cb4382e
