### ISSUE TITLE
msgstringtable#L1629 'again'

### ISSUE THREAD

**Issue by cydh** [ROClientSide/Translation#39]
https://github.com/ROClientSide/Translation/blob/master/data/msgstringtable.txt#L1629
````[%s] opened [%s] and awarded with '%s'!!#````

After this #33 effort, I just noticed recently that "**opened**" word is not good implementation.
The reason is, that line is used for type **0x0 for source is box/item** and **0x1 for source is monster** of packet `0x07fd`.
*You can try on Hercules that already has this ZC packet implemented*

The message will be
> [@cydh] **opened [Poring]** and awarded with 'Jellopy'!!

maybe.. still... this sounds better. :P
> Lady Luck shines upon [%s] !! [%s] has awarded the player with '%s' !!

and for type 0x2 is not a problem, it uses https://github.com/ROClientSide/Translation/blob/master/data/msgstringtable.txt#L1869
````Congratulation %s,  Acquired '%s' !#````
imho, just the extra spaces is weird. xD

**Comment by dastgir** [comment]
Lady Luck shines upon [Cydh] !! [Poring] has awarded the player with 'Jellopy' !!
Poring awarded xD

**Comment by kyeme** [comment]
In pRO:
Citizens of Midgard, Lady Luck shines upon [%s] !! [%s] has awarded the player with '%s' !!#

**Comment by dastgir** [comment]
I will update it with pRO ones.

**Comment by cydh** [comment]
pfft!!
on my last issue, I posted that line, but u reject me :sob:

**Comment by dastgir** [comment]
Stop trolling -_- ... Things changes..... I guess , my mind was influenced by someone else that time...

**Comment by dastgir** [comment]
3a06272be9fdcb4f5e78f741c395cc7c1cb4382e
