### ISSUE TITLE
Navigation in Korean

### ISSUE THREAD

**Issue by VeilsideGX** [ROClientSide/Translation#41]
Hi, just want to ask if this has been fixed before or if i need to use a different msgstring table. I'm on 2014-02-05 client. Please see attached.

![nav-kor](https://cloud.githubusercontent.com/assets/5967371/10038806/7db0e320-61fd-11e5-8b22-17946fc99f5d.png)

**Comment by dastgir** [comment]
We can't use Korean navigation, since we are behind kRO too much..
It's better to use https://github.com/HerculesWS/StaffPlugins/tree/master/Haru/naviluagenerator so that navigation will be generated according to your server mobs and npcs(name of npcs too)

**Comment by VeilsideGX** [comment]
I see thanks for the info. I just noticed it appeared initially from the new academy starting point and would probably confuse people who will receive navi popups.
