### ISSUE TITLE
msgstringtable.txt 

### ISSUE THREAD

**Issue by tsan79** [ROClientSide/Translation#43]
All the messages with %%  comes out like this
![50%ow](https://i.gyazo.com/aeb57e471182d87501d80962b86cd01a.png)
https://github.com/ROClientSide/Translation/blob/59f0f08adebebbe9f022f06f3ce5d3f65d43cfd3/data/msgstringtable.txt#L307

would removing the extra % effect the syntax in anyway?

**Comment by dastgir** [comment]
Probably not,
Double %% are required on lua files and not txt files, will be removed.

**Comment by dastgir** [comment]
3a06272be9fdcb4f5e78f741c395cc7c1cb4382e
