### ISSUE TITLE
stateiconinfo.lub issue

### ISSUE THREAD

**Issue by lelouch22** [ROClientSide/Translation#46]
![stateicon](https://cloud.githubusercontent.com/assets/4976551/12071467/ba55ee3e-b0e9-11e5-8178-c0f7457ef8e5.jpg)

**Comment by dastgir** [comment]
Fixed in https://github.com/ROClientSide/Translation/commit/bbb6341c58de9d8847d0f2edbf1c74ec1d13b063

**Comment by dastgir** [comment]
Thanks for reporting
