### ISSUE TITLE
idnum2itemdesctable does not work properly

### ISSUE THREAD

**Issue by bgamez23** [ROClientSide/Translation#49]
there is a bug for idnum2itemdesctable using 2012 clients. before the item description display properly but not using the latest version. it display nothing.

**Comment by bgamez23** [comment]
this is for pre-renewal

**Comment by dastgir** [comment]
Which item you tried?
And does it show name properly?

**Comment by bgamez23** [comment]
All of the item has no description but the item name display properly.but when i try to use the older version of idnum2itemdesctable.the description works fine.you can try it using 2012-04-10aRagexe client

**Comment by dastgir** [comment]
cb5f7f6c03fd19a7404b185701948939204225c1
Tried Some potions and WIngs, it doesn't happen on that client

**Comment by bgamez23** [comment]
I just only try the red potion item.

**Comment by dastgir** [comment]
Is it still the issue for you @bgamez?

**Comment by dastgir** [comment]
I tried again , its working for me.. can you take a screenshot?

**Comment by bgamez23** [comment]
ok hold on. im going to try it and also ill upload the client version that im using also the working and not working idnum2itemdesctable

**Comment by bgamez23** [comment]
here is the screenshot for the working one.
http://s21.postimg.org/ygaqy8kvb/screen_Milag_RO000.jpg

and here is the screenshot for the latest version which is not working.
http://s21.postimg.org/mpwtgus2v/screen_Milag_RO001.jpg

**Comment by bgamez23** [comment]
here is the client that im using also the working and not working idnum2itemdesctable
https://www.mediafire.com/?mhmlff15sdmxff6

**Comment by dastgir** [comment]
@bgamez23 
The non working one is old msgstring,(or you misnamed them)
also your working msgstring is almost half the size from the repo one.

**Comment by bgamez23** [comment]
Translation\Pre-Renewal\data\idnum2itemdesctable.txt
i just get it there the non working.
but the working one is my old ones which is work fine. maybe that's why its not working properly.

**Comment by dastgir** [comment]
http://imgur.com/4IoqdhJ

**Comment by dastgir** [comment]
@bgamez23 
Can you try this one?

https://mega.nz/#!tlRiRYzJ!ra6eCCwBEmR4v_3Zjpx-nOKs8Kdj3BywSLuv9e6Y6rY

**Comment by bgamez23** [comment]
the one that you send is works fine now.

**Comment by dastgir** [comment]
Thanks for reporting,
updated those files in the repo: https://github.com/ROClientSide/Translation/commit/c5115de4f4ba80a18d011404647051028417b335
Closing this. :)
