### ISSUE TITLE
Compare items windows have problem

### ISSUE THREAD

**Issue by hnomkeng** [ROClientSide/Translation#50]
Client date : 2015-09-16
Git version : 757

**Comment by dastgir** [comment]
What problem?

**Comment by hnomkeng** [comment]
use compare items (alt+e) is crash exe.

**Comment by dastgir** [comment]
I will check this tomorrow morning. Any custom item that you were wearing? Or does it happen every time?

**Comment by hnomkeng** [comment]
I'm test knife vs knife (item start.), other item same.

**Comment by hnomkeng** [comment]
vdo : https://youtu.be/lc8VRp_AV44

**Comment by kyeme** [comment]
I guess you switched from client 2013 to 2015, that's why you got this error. I suggest to update your data.grf or get the latest "comparison" from data/texture folder of kRO. 
btn_comparison_resize.bmp I guess

**Comment by hnomkeng** [comment]
@kyeme thank you for help, i'm copy basic_interface for kRO to fixed.
