### ISSUE TITLE
Class : High Wizard have problem(4010)

### ISSUE THREAD

**Issue by hnomkeng** [ROClientSide/Translation#51]
Client date : 2015-09-16

no use hdata.grf , use data git and data.grf(tRO) only

vdo : https://www.youtube.com/watch?v=kDKCsbU9cRg

**Comment by kyeme** [comment]
Please update you data/imf folder

**Comment by kyeme** [comment]
Or @dastgir can add this file

**Comment by hnomkeng** [comment]
@kyeme thank you for fixed :+1:

**Comment by dastgir** [comment]
It will be updated to this repo
