### ISSUE TITLE
Spiked Scarf & Rainbow Scarf Wrong Descriptions

### ISSUE THREAD

**Issue by lyleham** [ROClientSide/Translation#52]
Spiked scarf should have a description of :

Spiked Scarf (CORRECT)
VIT + 1.
Increase physical damage from Demi Human monster by 1%.
Reduces damage from Demihuman monster by 1%.
{ bonus bVit,1; bonus2 bAddRace,RC_DemiHuman,1; bonus2 bAddRace,RC_Player,1; bonus2 bSubRace,RC_DemiHuman,1; bonus2 bSubRace,RC_Player,1; },{},{}

Spiked Scarf (WRONG)
"ATK +30",
"MaxHP -2%",
"When using PC Gold Cafe, MaxHP +2%, ranged physical attack +2%, all stats +1.",

Rainbow Scarf (CORRECT)
Rainbow Scarf.
INT + 1. MDEF + 2.
MATK + 1%
{ bonus bInt,1; bonus bMdef,2; bonus bMatkRate,1; },{},{}

Rainbow Scarf (WRONG)
"MATK +30",
"MaxSP -2%",
"When using PC Gold Cafe, MaxSP +2%, reduce variable cast time by 2%, all stats +1.",

**Comment by lelouch22** [comment]
All descriptions are correct and based from kRO's itemInfo.lub

Spiked Scarf
kRO Descriptions:
ATK + 30, HP - 2%.
골드 PC방에서 사용 시, 추가로 HP + 2%, 원거리 물리 공격력 + 2%, All State + 1.

English:
ATK +30
MaxHP -2%
When using PC Gold Cafe, MaxHP +2%, ranged physical attack +2%, all stats +1.

Rainbow Scarf
kRO Descriptions:
MATK + 30, MSP - 2%.
골드 PC방에서 사용 시, 추가로 MSP + 2%, 변동캐스팅 시간 2% 단축, All State + 1.

English:
MATK +30
MaxSP -2%
When using PC Gold Cafe, MaxSP +2%, reduce variable cast time by 2%, all stats +1.

**Comment by dastgir** [comment]
The bonuses at emulator's are not always correct,  also description changes from time to time.
we follow kRO Description and not any emulator's script
