### ISSUE TITLE
Iteminfo.lua for Pre Renewal

### ISSUE THREAD

**Issue by reunite-ro** [ROClientSide/Translation#71]
Is there any updates on iteminfo,lua for pre-re ?
Seems like need to use old Client for Pre-re ?

**Comment by Asheraf** [comment]
i believe iteminfo file introduced in renewal so there is no official pre-re server that use it.

**Comment by reunite-ro** [comment]
So no content will be update ? I see okay :)

**Comment by dastgir** [comment]
If you feel data in pre renewal is incorrect, you can always open a PR :)

**Comment by reunite-ro** [comment]
its not that its incorrect, but there are some pre renewal item that are not listed in iteminfo.lua for pre-renewal for example angeling hat, poporing hat, etc. So pre-re iteminfo.lua could be use for new clients
