### ISSUE TITLE
Can't translate chat name

### ISSUE THREAD

**Issue by johnfercher** [ROClientSide/Translation#75]
I'm trying to translate the tabs of chat 'Regular Chat' and 'Battle Log', But without success.

Images from tabs:
https://i.gyazo.com/f0f2da7fd92ecdad46371fca58c19527.png

There are other messages in UI which aren't in msgstringtable.

**Comment by LiamKarlMitchell** [comment]
@johnfercher Those require hex modifications of the exe.
One could make a diff patch for nemo or something?

Fix Chat titles
```
ÀÏ¹Ý ¸Þ½ÃÁö' Replace with Main
¹èÆ² ¸Þ½ÃÁö' Replace with Battle
```

I might make one later if its needed.

**Comment by Akkarinage** [comment]
No translation required. You can set/store/change your default tab titles by providing your players with a "default" chat window options file. Patch in a savedata/ChatWndInfo_U.lua with some default states and you're good to go.

**Comment by LiamKarlMitchell** [comment]
Oh, even nicer to know.
Thanks @Akkarinage
